### ISSUE TITLE
Persist plugins

### ISSUE THREAD

**Issue by oren** [istepanov/docker-dokuwiki#1]
after backup and restore I noticed that my plugin (markdowku) is not installed. I am new to doku so i'll do my best to figure it out.

**Comment by dbu** [comment]
I assume the easiest way for this would be to create your own Dockerfile starting with `FROM istepanov/dokuwiki` and then either adding your plugins with shell commands in the Dockerfile or add the plugin folder to the symlinks like it is done for the data folders.

**Comment by istepanov** [comment]
I agree with @dbu. I'll update the readme file

**Comment by istepanov** [comment]
Readme updated: 846c428

**Comment by hrasyid** [comment]
Just curious (I'm new to docker and dokuwiki), but wouldn't symlinking /var/www/lib/plugins to var.dokuwiki-storage/lib/plugins work? That way it will be persisted like the rest of the data, no?
