### ISSUE TITLE
jQuery-UI Corrupt

### ISSUE THREAD

**Issue by kmlucy** [istepanov/docker-dokuwiki#17]
This seems to be an issue with this container, as opposed to the plugin as I initially thought: https://github.com/LotarProject/dokuwiki-template-bootstrap3/issues/257

**Comment by kmlucy** [comment]
I solved it. It turns out it was a permissions error on the ```/var/lib/nginx/``` directory, which was resulting in permission being denied to the fastcgi directory. I changed the directory owner and it looks like it is fixed now.

 I believe the issue stemmed somehow from a combination of my work in setting it up, and this image. I have not had the problem resurface even after rebuilding the container, so I'm not sure how it happened. I'm going to close out the issue for now, and will reopen if the issue reappears. 

Thanks,
Kyle

**Comment by Simon-L** [comment]
@kmlucy What was the permission error you had? And how did you fix it more precisely?
I've had issues too but I think they're linked to #19, #18 and #6 

I thought I might ask because I ended up looking at fixing things in `/var/lib/nginx/` as well.

Thanks in advance!

**Comment by kmlucy** [comment]
I don't remember precisely what the permission error is, but it still crops up occasionally. To fix it, I run: 
``` 
docker exec dokuwiki chown -R nobody:root /var/lib/nginx/
``` 
Then force a hard refresh of my wiki.
