### ISSUE TITLE
Container command /bin/sh not found or does not exist on new pull

### ISSUE THREAD

**Issue by apeltzer** [istepanov/docker-dokuwiki#9]
.... 
![screen shot 2016-07-18 at 15 58 39](https://cloud.githubusercontent.com/assets/2359510/16917134/a2bfadd8-4d00-11e6-82c5-15ff91580c1e.png)

Doesn't work anymore after latest push ...

**Comment by istepanov** [comment]
Can't reproduce this issue. I forced image rebuild on Docker Hub (just in case), so pull the image again and try to run it. If problem still exists, please reopen the issue.

**Comment by istepanov** [comment]
BTW, I've just noticed something strange in the command you used: `-p 8000:90`. The image uses 80 port internally, not 90, this command won't work. Use `-p 8000:80` instead.

**Comment by apeltzer** [comment]
Yes that was something weird with my docker installation. I restarted docker via systemctl and now things are back to normal behaviour. The -p thing was solved as well - had to map to a different port instead.
